apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdApp
metadata:
  name: insights-scheduler
spec:
  kafka:
    topics:
      - topicName: platform.notifications.ingress
        partitions: 6
        replicas: 3
        config:
          cleanup.policy: delete
          retention.ms: "2592000000"  # 30 days for production
          
  deployments:
    - name: service
      podSpec:
        # Production-specific environment variables
        env:
          - name: LOG_LEVEL
            value: WARN
          - name: EXPORT_SERVICE_TIMEOUT
            value: 10m
          - name: EXPORT_SERVICE_MAX_RETRIES
            value: "5"
          - name: DB_MAX_OPEN_CONNECTIONS
            value: "50"
          - name: DB_MAX_IDLE_CONNECTIONS
            value: "10"
          - name: KAFKA_RETRIES
            value: "10"
          - name: SHUTDOWN_TIMEOUT
            value: 60s
          
        # More aggressive probes for production
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Secret
metadata:
  name: insights-scheduler-secrets
stringData:
  # Production secrets should be managed externally
  # These are placeholders - use actual values from Vault or similar
  EXPORT_SERVICE_ACCOUNT: "${EXPORT_SERVICE_ACCOUNT_PROD}"
  EXPORT_SERVICE_ORG_ID: "${EXPORT_SERVICE_ORG_ID_PROD}"